# Generated by Django 6.0 on 2026-02-01 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tep', models.CharField(choices=[('active', 'Активний'), ('passive', 'Пасивний'), ('mixed', 'Змішаний')], max_length=20)),
                ('category', models.CharField(choices=[('econom', 'Econom'), ('standard', 'Standard'), ('luxe', 'Luxe')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rests')),
            ],
            options={
                'verbose_name': 'reevs_room',
                'verbose_name_plural': 'Rests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('total_rooms', models.PositiveIntegerField()),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='reevs.rest')),
            ],
            options={
                'verbose_name': 'rooms',
                'verbose_name_plural': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reevs.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bokings',
                'ordering': ['start_time'],
            },
        ),
    ]
