# Generated by Django 6.0 on 2026-01-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reevs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rest',
            options={'ordering': ['number'], 'verbose_name': 'reevs_room', 'verbose_name_plural': 'Rests'},
        ),
    ]
