# Generated by Django 6.0 on 2026-02-13 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reevs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='rest',
            options={'ordering': ['name'], 'verbose_name': 'rest', 'verbose_name_plural': 'rests'},
        ),
        migrations.AddField(
            model_name='booking',
            name='rest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='reevs.rest'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
