# Generated by Django 6.0 on 2026-01-26 16:57
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reevs', '0002_alter_rest_options'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE reevs_room RENAME TO reevs_rest;",
            reverse_sql="ALTER TABLE reevs_rest RENAME TO reevs_room;",
        ),
    ]
