# Generated by Django 6.0 on 2026-01-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reevs', '0003_rename_table_room_to_rest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rest',
            options={'ordering': ['name'], 'verbose_name': 'reevs_room', 'verbose_name_plural': 'Rests'},
        ),
        migrations.RemoveField(
            model_name='rest',
            name='number',
        ),
        migrations.AddField(
            model_name='booking',
            name='guests_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rest',
            name='name',
            field=models.CharField(default='DefaultName', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rest',
            name='tep',
            field=models.CharField(choices=[('active', 'Активний'), ('passive', 'Пасивний'), ('mixed', 'Змішаний')], default='active', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rest',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rest',
            name='category',
            field=models.CharField(choices=[('econom', 'Econom'), ('standard', 'Standard'), ('luxe', 'Luxe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rest',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='rests'),
        ),
    ]
